language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

script: ./gradlew check library:test

notifications:
  email: false
  slack:
    rooms:
      secure: 'b+Zuqd3bHR2cLseNibY8ChNHS+SekL6pT3pDOpFK7lu590WX0zRx86idX7I8w3KHNKpKY//oJXQGE/BwmznlsOxEGmr9PCQRMlUMY0lJg/aEyR1CrCwtmna5oUxF3fZq5zJ2D+X5MGZlJXEI4N2o6fhtWyTArlr+n0XSfByGq0Q1sCwnHNTb+PWkFeROr9tUroikftmY9DiLM0gUWjSr8yDHA5V/BOCpAijZJ+TuaC/VC89YUhbWuHqnvnSJlPfLGlpUZFUpqgaAP6rNJVOPZEhnqwKIY6uPk/5YOUyEpMUQV+DyFvBi994KlkmntSWNrPTlifzIJfj2NyzP/D/IZMMymvLCEePiH+xJYMFY8G7YENSqkqE9XYloufIzu8iz1e0BnEiHDKR+rreo838U3aQpMeV6nNw9ZwhVKnFbslDzsa9UcrPd//R06027nFanwgEp4rpcOr9Xcp8yZdwEqoYG7F5XIRN6hnX8lciboqnJNZ/HdoVc/cKQj1kfhcPZ0fkvWaAWUxOr5QnkA1XEESGThLjESKjHsrAJgpbdKTpOKMGtb+xxSGQ2j334UmCgBZXMgb9s8m9lS5ZaHsBbWs9c+f3vJEh5qMUTFLJN60k4aZad/XJxW5F4x5kvacbrOEDWNQ1hCVY2VVMVVu8UQj0OTpVF6MnYzWDJymkC18Y='
    on_success: change
