language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

script: ./gradlew check library:test

notifications:
  email: false
  slack:
    rooms:
      secure: ZGd8D0Wv15aRgDl5QAZJves8ttYCbTSUbF/WtpFZunoYQg5Cz0+0/YHnx9Hhwxnakg9n7r3kGXiugKOnsNW8jOJbYEIyxjt/OlT26HHgRh+VvI4l9vZYJRWkabjDAx+oAyyvGaQE5RrEzuak1wnGsdj5hc3PlTsA04tRLsdzIIuunnbLrE9UnsbMx2z9uPJWuYObgzJ6RLW2O4i/qhgsWKy4s4SUQph9BcF7I3wGc54uyaV3mmglXGWHvCHlODYCYYmEgW4E5iJ+KAUHTCSNNWcMGVX1Wo8l5PCjC1PHW39+ye9bzWSDBJtSla2hDAdrFp+RxpqbWVywCTDadiQzX7bbnBfUYiUjRbkCU7L/3d2bbFUaEamWmvto4K5Y84egT46vI6UwFFn9DJAwMzx35ARwDW8XZnNBwAbHIv57pChHoOvEb1X5YsZXD8tBMHHqE7zEow7gYRy67vIeVfRcAKfp6XclNgbUiwsdlm9MuZK1+fnsCHcQUIpcld25lc4l/R+BbcPHqQ31acjHrzpof2CEJdok8+0xWVDdiq0SK2pKJ92Q8+IfAXMIvEDmD/HHuVRV+HdyOcvQmTxlzHN1g8EP6GFsiF90e5xmcNfMjZ6zrk18oQNBCZznYJMnrVUWZU1/gg966+B+3M81tVlBfLP6mNbl7DSCfhaa/yrodGQ=
    on_success: change
