name: Build

on:
  push:

jobs:
  check:
    name: Run Check
    runs-on: ubuntu-18.04
    env:
      TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
      TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
      TEST_USER_IDX: ${{ secrets.TEST_USER_IDX }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Gradle caches cache
      uses: actions/cache@v2
      with:
        path: /home/runner/.gradle/caches
        key: caches-cache-ubuntu-18.04-v2
    - name: Gradle wrapper cache
      uses: actions/cache@v2
      with:
        path: /home/runner/.gradle/wrapper
        key: wrapper-cache-ubuntu-18.04-v2
    - name: Check
      run: ./gradlew check library:test
